require('kiran.barbar')
require('kiran.toggleterm')
require('kiran.nvim-tree')
require('kiran.cmp')
require('kiran.nvim-lsp-config')
require('kiran.mason')
require('kiran.treesitter')
require('kiran.opts')
require('kiran.keys')
require('kiran.language-specific')

require("nvim-autopairs").setup({})
